version: '3.7'
services:
  meu-mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

  rabbitmqTaxCalculator:
    image: rabbitmq:3.6.6-management
    container_name: 'rabbitmqTaxCalculator'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=123456